### ISSUE TITLE
Code incorrect while same in week 6: Storing Records

### ISSUE THREAD

**Issue by omit01** [EconometricInstitute/intro-programming-website#11]
While working through week 6 I got an error on the *Storing Records* exercise. After trying many different options I copied the code for the solution.

Looking into the test, it wants to test the *data2.txt* file. This file is not given in this exercise (It is given in the previous exercise.)

**Comment by nickwkoning** [comment]
Hmm I did fix an issue (raised by someone else through email) with the data2.txt file missing on the 28th of March. The previous issue was:
 
"I came across another error while working through the “Files and Reading Data” section, in the “Records from a file” assignment. I found out how to go to the tests and (with my mom’s help) found how to access all the files.
 
The test requires two files named, “data2.txt” and “recordsData.txt”, however the test folder only contains the “recordsData.txt” file, thus giving an error each time. We managed to add the file and check the code, but I think this error would be there for everyone as well when they try."

My reply was:
- The data2.txt file was somehow set to ‘hidden’, and therefore removed when putting together the ‘course file’.

Is this a distinct issue? Or perhaps you still have the old practice exercises from canvas?

**Comment by omit01** [comment]
I think it's a distinct, but closely related issue.

I downloaded the most recent file to check, but there is the file missing. Indeed, it's added in *Records from a file* assignment, but it's not in the assignment after it, *Storing Records*.

**Comment by nickwkoning** [comment]
Ah right, I spotted the issue. The file was in the material, but marked to be hidden for some reason.

Odd that the other student hadn't noticed it! Perhaps they just copied it from the previous assignment.

Anyway, it should be fixed now! I uploaded the new versions to Canvas.
