### ISSUE TITLE
Excercise Overloaded Counter already has solution

### ISSUE THREAD

**Issue by omit01** [EconometricInstitute/intro-programming-website#9]
**Discription**
Excercise *Overloaded Counter* in week 5 already has the correct solution in the Counter class.

**Expected behavior**
The Counter class is (almost) empty and you have to write you own code.

**Actual behavior**
The Couter class already has the right solution in it, so you only have to check the answer.

**Comment by nickwkoning** [comment]
That's odd.. If I open the practice exercises its properly masked (see screenshot and also the .zip file that I just downloaded from Canvas). Could you perhaps try to re-download them from Canvas and check if the issue persists?

[Introduction_to_Programming___Practice_Assignments_Week_5.zip](https://github.com/EconometricInstitute/intro-programming-website/files/6217388/Introduction_to_Programming___Practice_Assignments_Week_5.zip)


![Screenshot 2021-03-28 at 15 35 28](https://user-images.githubusercontent.com/26634002/112754177-3b463a00-8fdb-11eb-91e9-30cc24b9ee4c.png)

**Comment by nickwkoning** [comment]
I do know there were some masking issues before, and I fixed them. So it could be that this was fixed as well.

**Comment by omit01** [comment]
In the newer version it's fixed, I see. I had a version from 21 March.
